from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(312, 487)
        MainWindow.setMinimumSize(QtCore.QSize(312, 487))
        MainWindow.setMaximumSize(QtCore.QSize(312, 487))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #242b2d")
        self.centralwidget.setObjectName("centralwidget")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(50, 140, 221, 41))
        self.label_nome.setStyleSheet("background-color: rgb(76, 84, 86);\nborder: 1px solid black;\n")
        self.label_nome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nome.setObjectName("label_nome")
        self.label_senha = QtWidgets.QLabel(self.centralwidget)
        self.label_senha.setGeometry(QtCore.QRect(50, 240, 221, 41))
        self.label_senha.setStyleSheet("background-color: rgb(76, 84, 86);\nborder: 1px solid black;\n")
        self.label_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.label_senha.setObjectName("label_senha")
        self.line_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.line_nome.setGeometry(QtCore.QRect(50, 180, 221, 31))
        self.line_nome.setStyleSheet("background-color: rgb(195, 195, 195);\nborder: 1px solid black\n")
        self.line_nome.setObjectName("line_nome")
        self.line_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.line_senha.setGeometry(QtCore.QRect(50, 280, 221, 31))
        self.line_senha.setStyleSheet("background-color: rgb(195, 195, 195);\nborder: 1px solid black\n")
        self.line_senha.setObjectName("line_senha")
        self.button_login = QtWidgets.QPushButton(self.centralwidget)
        self.button_login.setGeometry(QtCore.QRect(50, 360, 221, 61))
        self.button_login.setStyleSheet("background-color: rgb(76, 84, 86);")
        self.button_login.setObjectName("button_login")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 320, 221, 31))
        self.widget.setStyleSheet("background-color: rgb(54, 59, 61);\nborder-radius: 25px;")
        self.widget.setObjectName("widget")
        self.radioButton_login = QtWidgets.QRadioButton(self.widget)
        self.radioButton_login.setGeometry(QtCore.QRect(30, 0, 81, 31))
        self.radioButton_login.setObjectName("radioButton_login")
        self.radioButton_cadastro = QtWidgets.QRadioButton(self.widget)
        self.radioButton_cadastro.setGeometry(QtCore.QRect(110, 0, 81, 31))
        self.radioButton_cadastro.setObjectName("radioButton_cadastro")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(10, 40, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_logo.setFont(font)
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 430, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_nome.setText(_translate("MainWindow", "nome"))
        self.label_senha.setText(_translate("MainWindow", "senha"))
        self.button_login.setText(_translate("MainWindow", "Entrar"))
        self.radioButton_login.setText(_translate("MainWindow", "Login"))
        self.radioButton_cadastro.setText(_translate("MainWindow", "Cadastro"))
        self.label_logo.setText(_translate("MainWindow", "Notepad Cipher"))
